version: "3"

networks:
  api_network:

services:
  api:
    build: .
    image: $DOCKER_IMAGE
    env_file:
      - .env
    logging:
      driver: json-files
      options:
        max-size: 10m
    ports:
      - $PORT:$PORT
    restart: always
  disk-plus-api-postgres:
    container_name: disk-plus-api-postgres
    image: postgres:alpine
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - api_network
    ports:
      - 5432:5432
    restart: always
    # volumes:
    #   - ./data:/var/lib/postgresql/data